apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-express-dep
  name: mongo-express-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express-dep
  template:
    metadata:
      labels:
        app: mongo-express-dep
    spec:
      containers:
      - image: mongo-express:latest
        name: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              key: mongodb-username
              name: mongodb-secret
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-password
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb-dep-svc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-express-dep
  name: mongo-express-svc
  namespace: default
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 31000
  selector:
    app: mongo-express-dep
  type: LoadBalancer