apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb-dep
  name: mongodb-dep
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mongodb-dep
  template:
    metadata:
      labels:
        app: mongodb-dep
    spec:
      containers:
      - image: mongo:latest
        name: mongodb
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-dep
  name: mongodb-dep-svc
  namespace: default
spec:
  ports:
  - port: 30000
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb-dep
  type: ClusterIP
